[project]
name = "backend"
version = "0.1.0"
description = "authentication demo with Flask"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "python-dotenv>=1.0.1",
]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
ignore = ["F401"]
